apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l3x3n2swv-dotnet-basic
  janus-idp.io/tekton: l3x3n2swv-dotnet-basic
  backstage.io/kubernetes-id: l3x3n2swv-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l3x3n2swv-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
